from .default import *

TESTING = True
DEBUG = True

APP_ENV = APP_ENV_TESTING
WTF_CSRF_ENABLED = False

SQLALCHEMY_DATABASE_URI = 'sqlite://'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False

APP_UPLOAD_FOLDER = '/tmp'